services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=dbCryptoCurrency'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=admin'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
